spring:
  datasource:
    url: jdbc:mysql://192.168.12.82:3306/app_spread
    username: app_spread
    password: RDlJ371E
    #    url: jdbc:mysql://192.168.20.3:3306/app_spread
    #    username: app_spread
    #    password: RDlJ371E
    #    url: jdbc:mysql://localhost:3306/app_spread
    #    username: root
    #    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    # Druid连接池配置，官方配置参考：https://github.com/alibaba/druid/tree/master/druid-spring-boot-starter
    druid:
      initial-size: 30 #初始化时建立物理连接的个数。初始化发生在显示调用init方法，或者第一次getConnection时
      max-active: 64 #最大连接池数量
      min-idle: 10 #最小连接池数量
      max-wait: 15000 #获取连接时最大等待时间，单位毫秒。配置了maxWait之后，缺省启用公平锁，并发效率会有所下降，如果需要可以通过配置useUnfairLock属性为true使用非公平锁
      use-unfair-lock: true
      validation-query: select 1 from dual # 验证连接有效与否的SQL，不同的数据配置不同
      test-on-borrow: false #申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
      test-on-return: false #归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
      test-while-idle: true #建议配置为true，不影响性能，并且保证安全性。申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效
      time-between-eviction-runs-millis: 10000 # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      web-stat-filter:
        enabled: true #是否启用StatFilter默认值true
        url-pattern:
      filters: stat,wall
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 2000
  redis:
    database: 4
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 1000
    redis:
      jedis:
        pool:
          max-active: 16
          max-idle: 300
          min-idle: 0
          max-wait: 10000

# Mybatis配置
mybatis:
  typeAliasesPackage: com.tj.spread.entity
  mapperLocations: classpath:mapper/*.xml
  configuration.mapUnderscoreToCamelCase: true
